"""
Report generation utilities for investigation results.
"""
from datetime import datetime
from typing import Dict, List, Any


class ReportGenerator:
    """Generate formatted investigation reports."""

    @staticmethod
    def generate_markdown_report(
        issue_description: str,
        logs: List[Dict[str, Any]],
        deployments: List[Dict[str, Any]],
        code_analysis: Dict[str, Any],
        timestamp: datetime = None
    ) -> str:
        """Generate a markdown-formatted investigation report.

        Args:
            issue_description: Description of the issue
            logs: Relevant log entries
            deployments: Recent deployments
            code_analysis: Code analysis results
            timestamp: Report generation timestamp

        Returns:
            Markdown-formatted report string
        """
        if timestamp is None:
            timestamp = datetime.utcnow()

        report = f"""# Production Issue Investigation Report

**Generated:** {timestamp.isoformat()}

## Issue Description
{issue_description}

## Investigation Summary

### Recent Deployments
{"No recent deployments found" if not deployments else f"{len(deployments)} deployment(s) found"}

### Log Analysis
{"No relevant logs found" if not logs else f"{len(logs)} log entries analyzed"}

### Code Analysis
{"No code changes analyzed" if not code_analysis else "Code analysis completed"}

---

*Report generated by Production Issue Investigator*
"""
        return report
